/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MosaicRestrictionTypeEnum } from './mosaicRestrictionTypeEnum';

export class MosaicGlobalRestrictionTransactionBodyDTO {
    /**
    * Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real  mosaic identifier. 
    */
    'mosaicId': string;
    /**
    * Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real  mosaic identifier. 
    */
    'referenceMosaicId': string;
    /**
    * Restriction key relative to the reference mosaic identifier.
    */
    'restrictionKey': string;
    /**
    * Previous restriction value.
    */
    'previousRestrictionValue': string;
    'previousRestrictionType': MosaicRestrictionTypeEnum;
    /**
    * New restriction value.
    */
    'newRestrictionValue': string;
    'newRestrictionType': MosaicRestrictionTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mosaicId",
            "baseName": "mosaicId",
            "type": "string"
        },
        {
            "name": "referenceMosaicId",
            "baseName": "referenceMosaicId",
            "type": "string"
        },
        {
            "name": "restrictionKey",
            "baseName": "restrictionKey",
            "type": "string"
        },
        {
            "name": "previousRestrictionValue",
            "baseName": "previousRestrictionValue",
            "type": "string"
        },
        {
            "name": "previousRestrictionType",
            "baseName": "previousRestrictionType",
            "type": "MosaicRestrictionTypeEnum"
        },
        {
            "name": "newRestrictionValue",
            "baseName": "newRestrictionValue",
            "type": "string"
        },
        {
            "name": "newRestrictionType",
            "baseName": "newRestrictionType",
            "type": "MosaicRestrictionTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return MosaicGlobalRestrictionTransactionBodyDTO.attributeTypeMap;
    }
}

