/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Type of transaction: * 0x414C (16716 decimal) - AccountLinkTransaction. * 0x4141 (16705 decimal) - AggregateCompleteTransaction. * 0x4241 (16961 decimal) - AggregateBondedTransaction. * 0x414D (16717 decimal) - MosaicDefinitionTransaction. * 0x424D (16973 decimal) - MosaicSupplyChangeTransaction. * 0x424E (16974 decimal) - AddressAliasTransaction. * 0x434E (17230 decimal) - MosaicAliasTransaction. * 0x4155 (16725 decimal) - MultisigAccountModificationTransaction. * 0x414E (16718 decimal) - NamespaceRegistrationTransaction. * 0x4148 (16712 decimal) - HashLockTransaction. * 0x4152 (16722 decimal) - SecretLockTransaction. * 0x4252 (16978 decimal) - SecretProofTransaction. * 0x4150 (16720 decimal) - AccountAddressRestrictionTransaction. * 0x4250 (16976 decimal) - AccountMosaicRestrictionTransaction. * 0x4350 (17232 decimal) - AccountOperationRestrictionTransaction. * 0x4151 (16721 decimal) - MosaicGlobalRestrictionTransaction. * 0x4251 (16977 decimal) - MosaicAddressRestrictionTransaction. * 0x4154 (16724 decimal) - TransferTransaction. 
*/
export enum TransactionTypeEnum {
    NUMBER_16716 = <any> 16716,
    NUMBER_16705 = <any> 16705,
    NUMBER_16961 = <any> 16961,
    NUMBER_16717 = <any> 16717,
    NUMBER_16973 = <any> 16973,
    NUMBER_16974 = <any> 16974,
    NUMBER_17230 = <any> 17230,
    NUMBER_16725 = <any> 16725,
    NUMBER_16718 = <any> 16718,
    NUMBER_16712 = <any> 16712,
    NUMBER_16722 = <any> 16722,
    NUMBER_16978 = <any> 16978,
    NUMBER_16720 = <any> 16720,
    NUMBER_16976 = <any> 16976,
    NUMBER_17232 = <any> 17232,
    NUMBER_16721 = <any> 16721,
    NUMBER_16977 = <any> 16977,
    NUMBER_16724 = <any> 16724
}
